name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      run: |
        IMAGE=lithu213/strapi-app:latest
        docker build -t $IMAGE .
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push $IMAGE

    - name: Export image tag
      id: image
      run: echo "::set-output name=tag::latest"

    outputs:
      image_tag: ${{ steps.image.outputs.tag }}